tune:
  mlflow:
    experiment_name: "OxfordIIITPet"
  batch_size: 8
  limit_train_batches: 0.1
  epochs: 10
  log_model: false
  n_workers: 4
train:
  mlflow:
    experiment_name: "OxfordIIITPet"
    run_name: "best_model"
  batch_size: 8
  epochs: 20
  patience: 5
  log_model: True
  n_workers: 4
optuna:
  pruner:
    n_startup_trials: 5
    n_warmup_steps: 3
  n_trials: 10
seed: 2023
